### ISSUE TITLE
用了这个EFI，安装都正常，但是WiFi和蓝牙都打不开，macOS Sonoma 14.4.1的系统

### ISSUE THREAD

**Issue by zifeng-chen** [zpyangchina/NUC9-hackintosh#1]
请问需要单独设置什么吗？期盼回复

**Comment by zpyangchina** [comment]
首先确认一下你用的什么网卡，如果是苹果拆机卡或博通免驱卡，sonoma需要打oclp补丁网卡才能正常工作，如果是自带的Intel AX200网卡，请下载对应的IntelWIFICard EFI，并使用最新的支持sonoma的网卡驱动替换掉原有的Ventura WIFI驱动，下载地址：https://github.com/OpenIntelWireless/itlwm，蓝牙打不开的情况看一下usb定制在sonoma下是否正常，如USB定制不正常请重新定制USB，如正常请重置NVRAM试试。

**Comment by zifeng-chen** [comment]
> 首先确认一下你用的什么网卡，如果苹果拆机卡或博通免驱卡，sonoma需要打oclp补丁网卡才能正常工作，如果自带的Intel AX200网卡，请下载对应的IntelWIFICard EFI，使用最新的支持sonoma的网卡驱动替换掉原有的Ventura WIFI驱动，下载地址：[https://github.com/OpenIntelWireless/itlwm，蓝牙打不开的情况看usb定制在sonoma下是否正常，如USB定制不正常请重新定制USB，如正常请重置NVRAM试试。](https://github.com/OpenIntelWireless/itlwm%EF%BC%8C%E8%93%9D%E7%89%99%E6%89%93%E4%B8%8D%E5%BC%80%E7%9A%84%E6%83%85%E5%86%B5%E7%9C%8B%E4%B8%80%E4%B8%8Busb%E5%AE%9A%E5%88%B6%E5%9C%A8sonoma%E4%B8%8B%E6%98%AF%E5%90%A6%E6%AD%A3%E5%B8%B8%EF%BC%8C%E5%A6%82USB%E5%AE%9A%E5%88%B6%E4%B8%8D%E6%AD%A3%E5%B8%B8%E8%AF%B7%E9%87%8D%E6%96%B0%E5%AE%9A%E5%88%B6USB%EF%BC%8C%E5%A6%82%E6%AD%A3%E5%B8%B8%E8%AF%B7%E9%87%8D%E7%BD%AENVRAM%E8%AF%95%E8%AF%95%E3%80%82)
板载的AX200网卡，蓝牙地址一直是NULL，想尽办法还是不行

**Comment by zpyangchina** [comment]
请提供一下你用的EFI，并打开Hackintool的蓝牙信息截图、usb信息截图。

**Comment by zifeng-chen** [comment]
> 请提供一下你用的EFI，并打开Hackintool的蓝牙信息截图、usb信息截图。

不用了，谢谢大佬，机器出问题了，感谢大佬百忙之中的帮助。
